<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-woocommerce_thumbnail size-w_8f6098</name>
   <tag></tag>
   <elementGuidId>06b4ea24-ff4c-4181-b85b-b55d40177f4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dswbm-sliders-28180']/div[2]/div/ul/li[15]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-27466.status-publish.instock.product_cat-home-decor.product_cat-showpieces-figurines.product_cat-table-organizer.has-post-thumbnail.sale.taxable.shipping-taxable.purchasable.product-type-simple.bx-clone > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > div.prod-img > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7cce722c-5f3f-4c3e-ad01-87957bed34ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/HD-736B.jpeg?v=1704353197</value>
      <webElementGuid>1fede730-7fee-4d52-b85d-12e9fbafda7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>513e8f6c-6037-4a70-95bd-432a57778fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Musical Men Metal Pen Holder/Desk Organizer Showpiece for office / home / gifts</value>
      <webElementGuid>3cebd610-2a29-4d77-bb2b-286498e27f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dswbm-sliders-28180&quot;)/div[@class=&quot;bx-wrapper&quot;]/div[@class=&quot;bx-viewport&quot;]/ul[@class=&quot;wbm-slider products&quot;]/li[@class=&quot;product type-product post-27466 status-publish instock product_cat-home-decor product_cat-showpieces-figurines product_cat-table-organizer has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple bx-clone&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/div[@class=&quot;prod-img&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>75515af6-8884-4518-9859-4653676ad56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dswbm-sliders-28180']/div[2]/div/ul/li[15]/a/div/img</value>
      <webElementGuid>8b2bae05-e78e-4127-9c34-ea4e6accc83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Musical Men Metal Pen Holder/Desk Organizer Showpiece for office / home / gifts'])[2]</value>
      <webElementGuid>f6da98c9-738a-46d9-9a76-f866d3f5bc48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/a/div/img</value>
      <webElementGuid>9df02390-25d9-48be-a1cf-884a0fd72dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2024/01/HD-736B.jpeg?v=1704353197' and @alt = 'Musical Men Metal Pen Holder/Desk Organizer Showpiece for office / home / gifts']</value>
      <webElementGuid>2dbde8c4-9e3c-4dc5-80f4-103273fe2db9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
