<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-woocommerce_thumbnail size-w_8f6098</name>
   <tag></tag>
   <elementGuidId>71d2dd22-ecc4-42d6-9e6e-86dc511c50ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-27466.status-publish.instock.product_cat-home-decor.product_cat-showpieces-figurines.product_cat-table-organizer.has-post-thumbnail.sale.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > div.prod-img > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dswbm-sliders-28180']/div[2]/div/ul/li[4]/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>28ad369e-70ca-4a5d-b473-9bc75b4bd1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/HD-736B.jpeg?v=1704353197</value>
      <webElementGuid>68d665cf-9e12-486c-94c7-282b439b81a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>3b5056c8-27c2-4120-afe3-d66901a09f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Musical Men Metal Pen Holder/Desk Organizer Showpiece for office / home / gifts</value>
      <webElementGuid>6fea59c2-d402-41ca-9d33-07b5e5c87a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dswbm-sliders-28180&quot;)/div[@class=&quot;bx-wrapper&quot;]/div[@class=&quot;bx-viewport&quot;]/ul[@class=&quot;wbm-slider products&quot;]/li[@class=&quot;product type-product post-27466 status-publish instock product_cat-home-decor product_cat-showpieces-figurines product_cat-table-organizer has-post-thumbnail sale taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/div[@class=&quot;prod-img&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>84f548c2-76bb-4f5e-a02c-09983dc73ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dswbm-sliders-28180']/div[2]/div/ul/li[4]/a/div/img</value>
      <webElementGuid>f1ae7202-cadd-40c9-864b-39e73139871a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Musical Men Metal Pen Holder/Desk Organizer Showpiece for office / home / gifts']</value>
      <webElementGuid>aedf4517-3f63-4440-9ccc-a941f7446d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/div/img</value>
      <webElementGuid>7af55e83-af89-4cd9-aa5f-829e67d32ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2024/01/HD-736B.jpeg?v=1704353197' and @alt = 'Musical Men Metal Pen Holder/Desk Organizer Showpiece for office / home / gifts']</value>
      <webElementGuid>1c44fa04-ac7d-4432-8577-404b6828aa12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
