<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_zoomImg</name>
   <tag></tag>
   <elementGuidId>443ead38-c9f2-4b9c-80ef-392f8727c3b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-5442']/div/div[3]/div/div[9]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-product-gallery__image.flex-active-slide > img.zoomImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>59b9acb9-119e-424a-892d-e713a74db39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e47646a5-9c67-4854-bb5a-5cb91b213a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/Mudha-069BLUE.jpeg?v=1701778078</value>
      <webElementGuid>480550bb-8b85-4776-95e5-b3fc05ae144c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zoomImg</value>
      <webElementGuid>4484d659-5580-4fb1-883c-d9a49963e214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-5442&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-5 images&quot;]/div[@class=&quot;flex-viewport&quot;]/div[@class=&quot;woocommerce-product-gallery__wrapper&quot;]/div[@class=&quot;woocommerce-product-gallery__image flex-active-slide&quot;]/img[@class=&quot;zoomImg&quot;]</value>
      <webElementGuid>002180d8-8179-462b-896f-9cf3c93d3a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-5442']/div/div[3]/div/div[9]/img</value>
      <webElementGuid>cf65c818-970c-499e-ad83-6bfa236eed6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/Mudha-069BLUE.jpeg?v=1701778078')]</value>
      <webElementGuid>29a9fd80-b6c8-45ab-b751-9a4c89d6ca79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/img</value>
      <webElementGuid>6773afa6-b3c5-41ae-89aa-c57424153e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/Mudha-069BLUE.jpeg?v=1701778078']</value>
      <webElementGuid>ae53d1e6-6dbb-4163-9353-a7a837fa1f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
