<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_wmc-current-currency</name>
   <tag></tag>
   <elementGuidId>d22cb6fa-aadc-4403-9a21-1d86ba167b90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='woocommerce-multi-currency-1']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.wmc-current-currency</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f65c6dbb-9b86-496a-8bcf-a8c7df542b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wmc-current-currency</value>
      <webElementGuid>9bccdfbc-3452-4a49-b70a-b7735207d400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;woocommerce-multi-currency-1&quot;)/div[@class=&quot;wmc-currency-wrapper&quot;]/span[@class=&quot;wmc-current-currency&quot;]</value>
      <webElementGuid>92236fee-f6f0-452d-a30d-3e77094a21b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='woocommerce-multi-currency-1']/div/span</value>
      <webElementGuid>482aeffc-105c-4e7d-bcf9-9b63d3a937da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>cf99a16d-9ceb-4a71-bf47-c0e2583b1d41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
