<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View cart</name>
   <tag></tag>
   <elementGuidId>55a3bfc1-0b95-4052-a6f4-2415452769b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.added_to_cart.wc-forward</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>488f1929-8d2b-4574-a64c-27b28c44dcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/cart/</value>
      <webElementGuid>b4a0e31b-c43e-44e4-85f3-3066dbe02b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>added_to_cart wc-forward</value>
      <webElementGuid>222772ab-9cc2-4211-82dd-5ee6f67b5862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View cart</value>
      <webElementGuid>830452d5-8a97-4b50-b80d-0980595db499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View cart</value>
      <webElementGuid>551f75fa-2a37-49d5-bb01-556a3b274392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-29579 status-publish first instock product_cat-uncategorized has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;added_to_cart wc-forward&quot;]</value>
      <webElementGuid>a194136e-e2f8-4e6b-94c6-96afa9040673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li/a[3]</value>
      <webElementGuid>47f72663-e65a-4ae4-a7c1-95159a22ccfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View cart')])[2]</value>
      <webElementGuid>8146a4b6-e6e3-45c5-b10e-1d9180f4316a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://craferia.com/cart/')])[5]</value>
      <webElementGuid>6f122756-92d0-4f76-b793-4272804136fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>f3dc54ed-8c79-49b1-9bdd-3d7c7bb0f945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/cart/' and @title = 'View cart' and (text() = 'View cart' or . = 'View cart')]</value>
      <webElementGuid>55fc478e-7ae6-419b-9b2f-73837f9a8725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
