<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select options</name>
   <tag></tag>
   <elementGuidId>030022de-e372-489c-9f3d-70a5198746e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-5442']/section/ul/li[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.product_type_variable.add_to_cart_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b720324-97f2-45bf-97e8-fb0baa81ee47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/round-handmade-mudha-set-for-home-office-garden-outdoor/</value>
      <webElementGuid>663370ec-a627-4206-8a96-e13cd4e1f58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bb5ce5c6-afeb-4727-829c-ca4ff5f679f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button product_type_variable add_to_cart_button</value>
      <webElementGuid>59f307e0-6411-4d8c-a8ce-befe889e4333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>5437</value>
      <webElementGuid>8ddd252c-490c-44a1-8d89-b7f9331640e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_sku</name>
      <type>Main</type>
      <value>Blue_mudha</value>
      <webElementGuid>83f61633-42fd-4a9b-bf6d-1abc53425fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select options for “Round Handmade  Mudha Set For Home Office Garden Outdoor”</value>
      <webElementGuid>d3303147-aa37-484d-a894-aa4a0cda62a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>This product has multiple variants. The options may be chosen on the product page</value>
      <webElementGuid>ea89e346-72c4-4df5-b593-647a20f5f4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>eedb9055-0996-4680-8e2c-f8cf7a15be2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select options</value>
      <webElementGuid>0003ef0a-03ef-4b5b-92a4-4982c37aa054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-5442&quot;)/section[@class=&quot;related products&quot;]/ul[@class=&quot;products columns-3&quot;]/li[@class=&quot;product type-product post-5437 status-publish instock product_cat-mudha-stools has-post-thumbnail taxable shipping-taxable purchasable product-type-variable&quot;]/a[@class=&quot;button product_type_variable add_to_cart_button&quot;]</value>
      <webElementGuid>399ad8ae-a8c7-4109-9440-4a13621a4a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-5442']/section/ul/li[2]/a[2]</value>
      <webElementGuid>d942e668-2f28-4ddc-8b49-4ae5d3b43124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select options')]</value>
      <webElementGuid>ecbdbabe-0068-4322-b1b6-31f1004d24d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://craferia.com/round-handmade-mudha-set-for-home-office-garden-outdoor/')])[2]</value>
      <webElementGuid>f75356a4-d7fa-41bb-9783-c779ddc404ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a[2]</value>
      <webElementGuid>88f9b1ca-872a-40f9-b25e-2fa6483b15b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/round-handmade-mudha-set-for-home-office-garden-outdoor/' and (text() = 'Select options' or . = 'Select options')]</value>
      <webElementGuid>547a6bac-338c-434a-b1b0-af2c7ba38507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
