<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_5 in stock</name>
   <tag></tag>
   <elementGuidId>bad237ca-ce9a-45a6-b168-17d1210029b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-5442']/div[2]/form/div/div/div[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.stock.in-stock</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5a7a5ef5-0d33-4132-8274-d5f5b94d4a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stock in-stock</value>
      <webElementGuid>79d062b1-de2b-4848-b607-3c92e931ebea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5 in stock</value>
      <webElementGuid>2f13888a-e126-4998-89f9-7dac68ad18f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-5442&quot;)/div[@class=&quot;summary entry-summary&quot;]/form[@class=&quot;variations_form cart&quot;]/div[@class=&quot;single_variation_wrap&quot;]/div[@class=&quot;woocommerce-variation single_variation&quot;]/div[@class=&quot;woocommerce-variation-availability&quot;]/p[@class=&quot;stock in-stock&quot;]</value>
      <webElementGuid>cbc4d2c9-c2ce-49fe-bac8-0804ea180b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-5442']/div[2]/form/div/div/div[3]/p</value>
      <webElementGuid>84205ab7-a56d-4022-91f4-c8aeb0054db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>ad802a88-fb4a-4a4e-9184-7ecd0adf5705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '5 in stock' or . = '5 in stock')]</value>
      <webElementGuid>447ee2ae-5b1e-4d77-b742-74680ac72ba3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
