<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pswp__button pswp__button--close</name>
   <tag></tag>
   <elementGuidId>b45ca9e6-171d-46ac-92e7-f11ce8fae796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pswp__button.pswp__button--close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf79111c-43c0-4dce-bc0b-55c04743e5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pswp__button pswp__button--close</value>
      <webElementGuid>9855daf5-6c51-42cf-8c30-bb08819d68c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close (Esc)</value>
      <webElementGuid>e7ff45f3-b252-4b3c-b310-b0505b447174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;product-template-default single single-product postid-5437 wp-custom-logo wp-embed-responsive theme-storefront woocommerce woocommerce-page woocommerce-demo-store woocommerce-js woocommerce-multi-currency-INR storefront-full-width-content storefront-secondary-navigation storefront-align-wide left-sidebar woocommerce-active&quot;]/div[@class=&quot;pswp pswp--supports-fs pswp--open pswp--notouch pswp--css_animation pswp--svg pswp--animated-in pswp--zoom-allowed pswp--visible pswp--has_mouse&quot;]/div[@class=&quot;pswp__scroll-wrap&quot;]/div[@class=&quot;pswp__ui pswp__ui--fit&quot;]/div[@class=&quot;pswp__top-bar&quot;]/button[@class=&quot;pswp__button pswp__button--close&quot;]</value>
      <webElementGuid>7001a8a9-0af6-4413-8e81-5a4237e68294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>46a9a325-16ef-49cc-9344-9ce35498187f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
