<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pswp__button pswp__button--arrow--right</name>
   <tag></tag>
   <elementGuidId>4c67d9cd-56a0-4918-886d-95538cfd159d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pswp__button.pswp__button--arrow--right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90c2677b-27ba-46a6-b30f-46a3d95cf620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pswp__button pswp__button--arrow--right</value>
      <webElementGuid>c43f9fbe-26be-4c7a-9c02-f57cfe1f26aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next (arrow right)</value>
      <webElementGuid>2a6daccb-d638-476b-a15e-6f8155a660a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;product-template-default single single-product postid-5437 wp-custom-logo wp-embed-responsive theme-storefront woocommerce woocommerce-page woocommerce-demo-store woocommerce-js woocommerce-multi-currency-INR storefront-full-width-content storefront-secondary-navigation storefront-align-wide left-sidebar woocommerce-active&quot;]/div[@class=&quot;pswp pswp--supports-fs pswp--open pswp--notouch pswp--css_animation pswp--svg pswp--animated-in pswp--zoom-allowed pswp--visible pswp--has_mouse pswp--zoomed-in&quot;]/div[@class=&quot;pswp__scroll-wrap&quot;]/div[@class=&quot;pswp__ui pswp__ui--fit&quot;]/button[@class=&quot;pswp__button pswp__button--arrow--right&quot;]</value>
      <webElementGuid>0b7d32ec-1115-453e-a81b-0aa22f298d18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>86689d21-134f-4902-9a73-35cd72a80b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
