<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_pswp__img</name>
   <tag></tag>
   <elementGuidId>d9330d86-ac07-468f-a7ff-f71f57666bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/Orange_mudha.jpg?v=1701778086')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d0ce3813-c4fe-4b42-9c70-25ebc63cb335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pswp__img</value>
      <webElementGuid>ad27901c-9c7f-48b7-8249-d7181ad8ebd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/Orange_mudha.jpg?v=1701778086</value>
      <webElementGuid>542a75d4-824b-4a8a-bb1b-2ec01d9b26a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;product-template-default single single-product postid-5437 wp-custom-logo wp-embed-responsive theme-storefront woocommerce woocommerce-page woocommerce-demo-store woocommerce-js woocommerce-multi-currency-INR storefront-full-width-content storefront-secondary-navigation storefront-align-wide left-sidebar woocommerce-active&quot;]/div[@class=&quot;pswp pswp--supports-fs pswp--open pswp--notouch pswp--css_animation pswp--svg pswp--animated-in pswp--zoom-allowed pswp--visible pswp--has_mouse pswp--zoomed-in&quot;]/div[@class=&quot;pswp__scroll-wrap&quot;]/div[@class=&quot;pswp__container&quot;]/div[@class=&quot;pswp__item&quot;]/div[@class=&quot;pswp__zoom-wrap&quot;]/img[@class=&quot;pswp__img&quot;]</value>
      <webElementGuid>b50b1a82-977c-498e-96fd-6a0d87ae9d2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/Orange_mudha.jpg?v=1701778086')])[2]</value>
      <webElementGuid>e041d6b7-6102-4e3e-90e7-d17db1c71d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>cc1999ba-586d-4ecc-9b9d-34034533fa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/Orange_mudha.jpg?v=1701778086']</value>
      <webElementGuid>d79537c2-e325-469e-a554-d626f674e26c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
