<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pswp__button pswp__button--arrow--left</name>
   <tag></tag>
   <elementGuidId>93f118c0-41bc-49fb-883a-4ad7f12bd08c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pswp__button.pswp__button--arrow--left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1478520a-d010-4289-a498-0590aa8e0574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pswp__button pswp__button--arrow--left</value>
      <webElementGuid>02cd7018-ce85-4c5b-904c-b84fd3d446ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous (arrow left)</value>
      <webElementGuid>21a3e698-9eb5-4352-b076-bb95b6c0244e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;product-template-default single single-product postid-5437 wp-custom-logo wp-embed-responsive theme-storefront woocommerce woocommerce-page woocommerce-demo-store woocommerce-js woocommerce-multi-currency-INR storefront-full-width-content storefront-secondary-navigation storefront-align-wide left-sidebar woocommerce-active&quot;]/div[@class=&quot;pswp pswp--supports-fs pswp--open pswp--notouch pswp--css_animation pswp--svg pswp--animated-in pswp--zoom-allowed pswp--visible pswp--has_mouse&quot;]/div[@class=&quot;pswp__scroll-wrap&quot;]/div[@class=&quot;pswp__ui pswp__ui--fit&quot;]/button[@class=&quot;pswp__button pswp__button--arrow--left&quot;]</value>
      <webElementGuid>a5b09ed3-428f-45ce-944a-5aa0f4840759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>66695738-79bf-4cb7-91ba-798d41350ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
