<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_zoomImg</name>
   <tag></tag>
   <elementGuidId>92c011da-dda5-4782-821b-cf4b60988c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-5437']/div/div[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.zoomImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9b2b5137-ef45-45ad-82ad-e1eb1e117b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>750eb1c7-c55d-48b3-951c-2906ab768d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/Blue_mudha-1.jpg?v=1701778088</value>
      <webElementGuid>65237bfe-ca70-4f7f-8294-b08b022d25f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zoomImg</value>
      <webElementGuid>5e0b1163-85fa-496b-b43a-091cea89722b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-5437&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-5 images&quot;]/div[@class=&quot;flex-viewport&quot;]/div[@class=&quot;woocommerce-product-gallery__wrapper&quot;]/div[@class=&quot;woocommerce-product-gallery__image flex-active-slide&quot;]/img[@class=&quot;zoomImg&quot;]</value>
      <webElementGuid>a503758d-b99a-4447-ae4b-abeb120d39e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-5437']/div/div[3]/div/div/img</value>
      <webElementGuid>729bfca4-755b-443b-8ca3-35c55e3f6a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/Blue_mudha-1.jpg?v=1701778088')]</value>
      <webElementGuid>ae1ab6be-d10f-4579-8cb8-de2c124309c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>96a54b0e-0072-40a2-aaf6-b68a58803f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/Blue_mudha-1.jpg?v=1701778088']</value>
      <webElementGuid>5ae32148-ed9d-4542-b6da-b32456b7f6b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
