<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to cart</name>
   <tag></tag>
   <elementGuidId>7894409b-3e3a-4970-934e-8d47b8cbd874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/div[11]/ul/li[3]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>698d55f5-44e3-4b99-b2b3-070028326e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?add-to-cart=29579</value>
      <webElementGuid>072f0391-a166-4401-9f2d-a5d4d5f97375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add “Handmade Bamboo Mudda Chair (Set of 2) with Arm Rest- Black Color -XL size with Table” to your cart</value>
      <webElementGuid>78f74011-7057-45d3-b8a3-79ab439d16da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7551651b-44d2-427c-9e0d-495005b5c177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>29579</value>
      <webElementGuid>94f06b96-fe3a-4a58-9be5-b5dc861d20e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_sku</name>
      <type>Main</type>
      <value>MUDHA-0100set</value>
      <webElementGuid>d5799af1-487d-431a-81ef-2e4253ade9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>b2ce9c03-a1f9-444c-91fa-2cb438b2d91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-button__link  add_to_cart_button ajax_add_to_cart</value>
      <webElementGuid>d83cad59-43db-4ab1-8ab3-b7e140c6738e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>070b0928-80b5-41f0-8c44-d65b2753db86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;page-description&quot;]/div[@class=&quot;wc-block-grid wp-block-product-new wc-block-product-new has-5-columns has-multiple-rows&quot;]/ul[@class=&quot;wc-block-grid__products&quot;]/li[@class=&quot;wc-block-grid__product&quot;]/div[@class=&quot;wp-block-button wc-block-grid__product-add-to-cart&quot;]/a[@class=&quot;wp-block-button__link  add_to_cart_button ajax_add_to_cart&quot;]</value>
      <webElementGuid>c5369d18-8379-4a4b-bea5-bf8c55b05f8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/div[11]/ul/li[3]/div[2]/a</value>
      <webElementGuid>26e9b928-4d6d-4e99-97b9-8375a9b962fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add to cart')])[11]</value>
      <webElementGuid>e46f70f8-80a3-4962-9cd0-30b303867e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?add-to-cart=29579')]</value>
      <webElementGuid>207e1e56-1b66-43a7-9c32-b6e1b0cad694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/ul/li[3]/div[2]/a</value>
      <webElementGuid>7ae022d7-4bd9-4ef7-8faa-006cfb52be40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?add-to-cart=29579' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>e4436b76-e40e-4300-8090-0230f6b20ddd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
