<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>6c11bed1-77fa-48b3-ba66-abb560bc710e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/div[2]/div[2]/div/figure/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>figure.aligncenter.size-full.is-resized > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f823562-f2e8-4089-b890-a8c2cdc43349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/outdoor-furniture/</value>
      <webElementGuid>083d71a0-0c2d-402f-b4df-a309e5b06640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;page-description&quot;]/div[@class=&quot;wp-block-columns alignwide Banner_class has-background is-layout-flex wp-container-core-columns-layout-3 wp-block-columns-is-layout-flex&quot;]/div[@class=&quot;wp-block-column Banner_offer_valentine_Box is-layout-flow wp-block-column-is-layout-flow&quot;]/div[@class=&quot;wp-block-image is-style-rounded&quot;]/figure[@class=&quot;aligncenter size-full is-resized&quot;]/a[1]</value>
      <webElementGuid>cf76ab44-012f-4348-9ef0-41d82b06a548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/div[2]/div[2]/div/figure/a</value>
      <webElementGuid>8e8edeca-2cbb-44cc-bc7a-f7d9d7cdc892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://craferia.com/outdoor-furniture/')])[3]</value>
      <webElementGuid>803cd762-a018-47f4-968a-d60916340773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/figure/a</value>
      <webElementGuid>e3991701-6f1d-476e-bceb-b1ea9193a493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/outdoor-furniture/']</value>
      <webElementGuid>e4e87230-8018-4cbb-87cf-19255d4d168c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
