<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View cart</name>
   <tag></tag>
   <elementGuidId>21eb6e41-9096-422e-aa22-80a710c36cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/div[11]/ul/li[3]/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.added_to_cart.wc-forward</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43149396-ee09-478f-8a40-c952a11221f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/cart/</value>
      <webElementGuid>11bea047-86d8-47ba-b10d-78520ecdb4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>added_to_cart wc-forward</value>
      <webElementGuid>6b6dc92c-fffb-4daf-9a18-75a7cbdfaa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View cart</value>
      <webElementGuid>b0a5e1b5-028b-4af1-b703-cc39d9d1e2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View cart</value>
      <webElementGuid>1451fe13-6415-4d83-b127-63022d302e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;page-description&quot;]/div[@class=&quot;wc-block-grid wp-block-product-new wc-block-product-new has-5-columns has-multiple-rows&quot;]/ul[@class=&quot;wc-block-grid__products&quot;]/li[@class=&quot;wc-block-grid__product&quot;]/div[@class=&quot;wp-block-button wc-block-grid__product-add-to-cart&quot;]/a[@class=&quot;added_to_cart wc-forward&quot;]</value>
      <webElementGuid>8f00cd17-149a-4f40-9646-05928bb274f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/div[11]/ul/li[3]/div[2]/a[2]</value>
      <webElementGuid>48fc7677-67be-4b7e-93ed-cc3362679b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View cart')])[2]</value>
      <webElementGuid>48d8a21e-7a50-42bb-87e5-a672f08bbe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://craferia.com/cart/')])[5]</value>
      <webElementGuid>7de369b8-f9f1-4554-a2a2-c2ba05194193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]/a[2]</value>
      <webElementGuid>53842435-dc8c-4b02-bb9f-f89237f43706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/cart/' and @title = 'View cart' and (text() = 'View cart' or . = 'View cart')]</value>
      <webElementGuid>7e996e2d-1c3b-491b-87a3-11bafd38d4e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
