<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mudha Stools</name>
   <tag></tag>
   <elementGuidId>35dc684f-bdea-4f64-bed6-e23c0bb75a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26705']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26705 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30e19411-aeb4-4f16-bf7e-e483ce17d3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/mudha-stools/</value>
      <webElementGuid>b0adc33e-9f63-48f4-ba0f-156882102585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mudha Stools</value>
      <webElementGuid>e187b030-f5a4-4834-b8b6-92a5c4431a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26705&quot;)/a[1]</value>
      <webElementGuid>d41d7eff-1454-4e45-84c0-4173abea9c13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26705']/a</value>
      <webElementGuid>73fd395a-005d-48c1-9694-9be4d6577767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mudha Stools')]</value>
      <webElementGuid>969bb8c2-88f8-48d0-b147-4763b5c62fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/mudha-stools/')]</value>
      <webElementGuid>aa93a842-5a8f-406c-ab3a-e3bc784d3c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/a</value>
      <webElementGuid>cca277d0-189a-4542-ac8d-753427c6f01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/mudha-stools/' and (text() = 'Mudha Stools' or . = 'Mudha Stools')]</value>
      <webElementGuid>7539f722-6966-436d-820b-51b66059ec8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
