<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delhi</name>
   <tag></tag>
   <elementGuidId>55d80439-6d70-428c-bdb2-b661c8a99b40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-billing_state-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-billing_state-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa4ab62d-816c-49c8-980a-d20ccb300c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1128ecb5-356e-47cd-b8a3-7cdaa362d34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-billing_state-container</value>
      <webElementGuid>d0a10f20-4c81-4549-a430-ef1a2108818f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>5c1fcbab-1076-474b-9149-cf04e8d367d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e9e07f37-e534-4d8b-8bb4-7b0e58bd7fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delhi</value>
      <webElementGuid>56ed2be4-26cd-49c2-83b8-3cd54fd05f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delhi</value>
      <webElementGuid>51ee64d6-6df8-4ad7-8704-8b63c53e736a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_state-container&quot;)</value>
      <webElementGuid>7a7ee004-10b9-4285-be70-6c07a53c8911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-billing_state-container']</value>
      <webElementGuid>72aacbc8-0686-417e-89da-711b00676d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_state_field']/span/span/span/span/span</value>
      <webElementGuid>87954a5b-47c4-4ba6-8cd5-ff61efb91548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/span/span/span/span/span</value>
      <webElementGuid>77f7ab00-3f3c-4db1-9b5c-e477e29a4968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-billing_state-container' and @title = 'Delhi' and (text() = 'Delhi' or . = 'Delhi')]</value>
      <webElementGuid>1f32b96d-04a5-4d60-b172-1b6fedbc8d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
