<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Craferia_MyAccount_login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4d72fcf6-d2aa-459c-9588-30c0a6f930af</testSuiteGuid>
   <testCaseLink>
      <guid>08c24f92-efd5-437b-8a82-c0d640ade406</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>f220c46b-e6c0-4fe8-abc9-f52173bd25b8</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/tc_craferia_login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f481d99a-93d1-4714-a88a-7b09af66fec3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/craferia_login_test</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f481d99a-93d1-4714-a88a-7b09af66fec3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username </value>
         <variableId>f220c46b-e6c0-4fe8-abc9-f52173bd25b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f481d99a-93d1-4714-a88a-7b09af66fec3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1fd4c5d5-48c2-443c-8f74-eabccb6e996a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
