<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Home Decorative Items  Gifts Enhancing Y_c27759</name>
   <tag></tag>
   <elementGuidId>715698a8-8839-4e65-b0a9-86778ac50d4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main > h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5ee49d7c-ea95-47a9-a55a-dd7907f3e83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home Decorative Items &amp; Gifts: Enhancing Your Space with Exquisite Handicrafts</value>
      <webElementGuid>ab902f69-3abf-49ee-94e1-f965fd57aefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/h2[1]</value>
      <webElementGuid>33f067e0-6a27-479b-b80f-5a1af582ea6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/h2</value>
      <webElementGuid>ed5b9291-17d0-49d6-b7f0-d77b84c61907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/h2</value>
      <webElementGuid>72a4e09a-86a0-4e00-a584-afe09bd9f161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Home Decorative Items &amp; Gifts: Enhancing Your Space with Exquisite Handicrafts' or . = 'Home Decorative Items &amp; Gifts: Enhancing Your Space with Exquisite Handicrafts')]</value>
      <webElementGuid>67a842e8-40f1-45e5-9b9d-30d4391a60f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
