<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>c239a610-53c2-4e14-9e33-e74b7c092e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='buttons']/span/a[3])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payLaterMain > #buttons > span.content-text > a.secondary-link.cancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b288972c-cc33-4d5d-9b04-fadcc14f7f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5b171b72-4b39-4765-b1f6-77e01bfd0f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary-link cancel</value>
      <webElementGuid>7335f1c1-f122-4fca-9f78-c96f97f69c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>52228450-0ecf-40e0-8438-532300fd54c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payLaterMain&quot;)/div[@id=&quot;buttons&quot;]/span[@class=&quot;content-text&quot;]/a[@class=&quot;secondary-link cancel&quot;]</value>
      <webElementGuid>d172e251-d355-451d-b6b9-cca878736438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Handicrafts Online, Indian _dcf088/iframe_paymentFrame</value>
      <webElementGuid>0665a676-01ae-4e0d-b456-6ad2da083117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='buttons']/span/a[3])[5]</value>
      <webElementGuid>d38e2cad-fa3c-40ca-9742-a9166996a3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cancel')])[7]</value>
      <webElementGuid>110830b9-81dc-4b42-9a57-9ecc5c4ffbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[19]</value>
      <webElementGuid>a53fbd3b-1105-4dc4-9b53-a1ba4c2e0b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span/a[3]</value>
      <webElementGuid>537e8433-9143-4c0c-9db9-b50ba6674602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>8394d7f1-9eb3-48e2-9a33-cfd320393368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
