<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Order received</name>
   <tag></tag>
   <elementGuidId>55d130e4-76af-47a9-88de-fed9633d672e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-8']/header</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header.entry-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>72b4ffde-72a7-48ad-936a-b1008509c56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry-header</value>
      <webElementGuid>8b5e882b-3005-456c-ab7d-4c41db9203dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			Order received		</value>
      <webElementGuid>10b5f703-b81c-41f9-af0c-f3b825368a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-8&quot;)/header[@class=&quot;entry-header&quot;]</value>
      <webElementGuid>da4c97a2-2e29-4c1c-892f-1180f4463b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-8']/header</value>
      <webElementGuid>2e02d007-8f07-4713-95fc-2f1a6734c327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/header</value>
      <webElementGuid>a9edbb1b-bd60-42fb-a9c9-2673f74d7dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = '
			Order received		' or . = '
			Order received		')]</value>
      <webElementGuid>6f6f4f6b-2f4b-40bf-a896-beb9053a7f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
