<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_topPayLaterradio</name>
   <tag></tag>
   <elementGuidId>81b3a4e4-4ecb-40e3-bb73-b286873e3fff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlexiPay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlexiPay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b787586-94d1-4242-b8dd-38374d1ed509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>00a44eab-e53b-41f1-85ba-2661552862d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topPayLaterradio</value>
      <webElementGuid>45098bac-da3f-4200-af29-af498ab23337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio topPayLater</value>
      <webElementGuid>19f1305b-5b9b-4920-84db-a1e0d3b5f852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FlexiPay</value>
      <webElementGuid>c4992b47-d2b8-4c3c-a1fd-f738a22fbc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlexiPay</value>
      <webElementGuid>45732567-7b8d-434b-a94e-581ee3a35ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlexiPay&quot;)</value>
      <webElementGuid>12b7c5b7-9659-4466-a1ad-e635e654fadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Handicrafts Online, Indian _dcf088/iframe_paymentFrame</value>
      <webElementGuid>49bd7dfc-46b1-43df-badb-ec5d0ef5a697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlexiPay']</value>
      <webElementGuid>490d0fd7-7c2f-42f4-a108-c167d187a710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payLaterMain']/div[2]/span/label/input</value>
      <webElementGuid>41c59bca-8ba4-423a-b5d6-6d1505e1e2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/span/label/input</value>
      <webElementGuid>98995339-f2dc-448a-8853-557c0df1f3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'topPayLaterradio' and @id = 'FlexiPay']</value>
      <webElementGuid>9df407dd-0909-466a-8a7b-8ef0eed46a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
