<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_flexiPayMobileNumber</name>
   <tag></tag>
   <elementGuidId>ef2b12fb-857a-4cdf-90fd-832e07a8fe65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexiPayMobileNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flexiPayMobileNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78caa06b-def8-4c87-88c6-d5723cc22835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span12 textfield noradius onlynumbers</value>
      <webElementGuid>0adfecd5-b117-40dd-9b89-db9786529faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53dc2483-1dca-47aa-a0dd-08abaddc1d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flexiPayMobileNumber</value>
      <webElementGuid>29e1f832-1a44-4826-825b-2f98aecd1020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexiPayMobileNumber</value>
      <webElementGuid>7830cff8-7c6c-4123-9938-4becbdca94af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fecf68f0-463f-4056-b45f-bfc0220c52de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>d05d6353-84b1-495e-833a-327280178654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>456e1a57-f3bb-4563-9e13-1e6dbb789b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexiPayMobileNumber&quot;)</value>
      <webElementGuid>d100e265-ff28-4e87-a224-33075aeb2222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Handicrafts Online, Indian _dcf088/iframe_paymentFrame</value>
      <webElementGuid>bcf17e70-88aa-4e1a-af0c-2ed8beec664d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexiPayMobileNumber']</value>
      <webElementGuid>33088e67-8717-4097-b19e-3358ade42a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flexiPayMobileNo']/input</value>
      <webElementGuid>686738b2-4481-4168-b3db-988ad5d33c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>4140997a-1629-4799-916f-901ee3053d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'flexiPayMobileNumber' and @id = 'flexiPayMobileNumber']</value>
      <webElementGuid>6c8c03a7-66c9-4bb3-acd6-6b97558f6f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
