<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CancelTransaction</name>
   <tag></tag>
   <elementGuidId>590c9b4a-f8c1-490d-a7e5-6035c3179961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='buttons']/span/a/span)[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.primary-button.primary-button-bg.radius4.confirmCancel > span.primary-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3995f42-bcd7-427c-8df8-3aee1fa18ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-button-text</value>
      <webElementGuid>0176f139-2967-4487-a9da-e7d2c636584e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel Transaction</value>
      <webElementGuid>d0bc6526-7f02-4f1a-b883-83b507b0b0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel-transaction-feedback&quot;)/span[@class=&quot;span12 content&quot;]/table[1]/tbody[1]/tr[8]/td[2]/div[@id=&quot;buttons&quot;]/span[@class=&quot;content-text&quot;]/a[@class=&quot;primary-button primary-button-bg radius4 confirmCancel&quot;]/span[@class=&quot;primary-button-text&quot;]</value>
      <webElementGuid>c99676ec-d739-43ed-83c4-dd5899f42958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Handicrafts Online, Indian _dcf088/iframe_paymentFrame</value>
      <webElementGuid>54920418-51f3-4614-8bd2-e1ba88e246ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='buttons']/span/a/span)[15]</value>
      <webElementGuid>d5a85c60-990e-4ac2-b6af-7ca1a26073b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span/a/span</value>
      <webElementGuid>bf9e6fe0-00e2-413b-ad32-7c635d88db19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cancel Transaction' or . = 'Cancel Transaction')]</value>
      <webElementGuid>41ae5561-cb52-4336-a6a2-aa8e92756e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
