<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue</name>
   <tag></tag>
   <elementGuidId>813b35bf-f2be-4f74-b3f8-77cbac419295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='buttons']/span/a/span)[13]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.primary-button.primary-button-bg.radius4.btn-flexiPay-chkeligibility > span.primary-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>708406df-2c62-4144-adac-f3308d688ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-button-text</value>
      <webElementGuid>56b536f3-0300-4b3e-b9f4-bf40bf522281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>9a9ccd97-5571-4a4a-9e9e-47b5708e96c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payLaterMain&quot;)/div[@id=&quot;buttons&quot;]/span[@class=&quot;content-text&quot;]/a[@class=&quot;primary-button primary-button-bg radius4 btn-flexiPay-chkeligibility&quot;]/span[@class=&quot;primary-button-text&quot;]</value>
      <webElementGuid>d2902c1c-5b35-4344-a343-0a525d5b767e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Handicrafts Online, Indian _dcf088/iframe_paymentFrame</value>
      <webElementGuid>f8db151f-13bd-4b2a-818b-14219a725668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='buttons']/span/a/span)[13]</value>
      <webElementGuid>d8235149-33a3-41d2-a1e6-3136c7f7d71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span/a/span</value>
      <webElementGuid>a1148879-2e82-44f0-a2b5-799693f58dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>cc139a36-3d5f-475f-b8c3-c5bd2dc7b974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
