<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Make Payment</name>
   <tag></tag>
   <elementGuidId>d97b09a1-4ca3-4064-bb2e-85918b1134c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SubmitBillShip']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmitBillShip > span.primary-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8c476ed-93ec-494b-9cb0-2e3c3df0b8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-button-text</value>
      <webElementGuid>9e7d2a8c-c1ac-40fb-b35c-0afd13e972e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Make Payment</value>
      <webElementGuid>b08897e2-2dc0-4d03-a1c7-e642095baa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verticalTab&quot;)/div[@class=&quot;resp-tabs-container content-bg content-text border radius4 span9&quot;]/div[@class=&quot;tabcontent OPTCRDC resp-tab-content resp-tab-content-active&quot;]/div[@id=&quot;creditcard_form&quot;]/div[@id=&quot;buttons&quot;]/span[@class=&quot;content-text&quot;]/a[@id=&quot;SubmitBillShip&quot;]/span[@class=&quot;primary-button-text&quot;]</value>
      <webElementGuid>cc5af5db-b0a7-4464-a369-8a12976e2dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Handicrafts Online, Indian _dcf088/iframe_paymentFrame</value>
      <webElementGuid>cff42a17-9ac2-447c-a304-889a68c02007</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='SubmitBillShip']/span</value>
      <webElementGuid>5ab4329d-2e3c-41b7-b28d-e4582c6b8216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>f443c7c1-ae3b-46a5-a900-0370216eea54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Make Payment' or . = 'Make Payment')]</value>
      <webElementGuid>65db4f05-80bf-481a-94f9-acbee1fcbb99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
