<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mudha Stools</name>
   <tag></tag>
   <elementGuidId>7f33f771-dedd-4588-b852-e8232a36dc58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26705']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26705 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>adba22c0-a7df-4cc1-b6d7-c3265eeb1674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/mudha-stools/</value>
      <webElementGuid>c7ba506b-8f65-4520-9ef3-2bb2ba9a10e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mudha Stools</value>
      <webElementGuid>8b11d227-01de-4242-9a5c-e5530458452e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26705&quot;)/a[1]</value>
      <webElementGuid>0158091b-56b5-4f65-9798-b1eb3b74c7d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26705']/a</value>
      <webElementGuid>0b19f744-dcd4-4d32-89e8-9ec5eb312aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mudha Stools')]</value>
      <webElementGuid>94154f88-c076-4046-bbdf-41ed9c2258aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/mudha-stools/')]</value>
      <webElementGuid>48215d85-9a8d-4257-a160-13d90848f127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/a</value>
      <webElementGuid>3ec202e2-224b-4bc0-8a73-bd82ee39fe5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/mudha-stools/' and (text() = 'Mudha Stools' or . = 'Mudha Stools')]</value>
      <webElementGuid>1a8dca1f-bcc1-4ba9-89b1-311a948e6824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
