<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mudha</name>
   <tag></tag>
   <elementGuidId>bf34bc79-569a-4e78-b30a-3aa2e0bd7e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26704']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26704 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ed50164-1313-4ff6-805b-50166a37a6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/mudha/</value>
      <webElementGuid>4139553c-81cb-4fc6-bb80-e001d56979f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mudha</value>
      <webElementGuid>08c035dc-db58-44c7-9669-7319b4861d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26704&quot;)/a[1]</value>
      <webElementGuid>5848cde1-66c6-4bbd-978d-62129a35138c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26704']/a</value>
      <webElementGuid>893556b2-bad7-4f17-a804-5ae19f67bc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Mudha')])[3]</value>
      <webElementGuid>13f8b594-5e9f-4f62-8bf1-3e844426c95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/mudha/')]</value>
      <webElementGuid>32f2fd81-0eea-44f6-ae4c-25f996d25468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>2b0377c4-17c8-4e38-8149-59b026fea612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/mudha/' and (text() = 'Mudha' or . = 'Mudha')]</value>
      <webElementGuid>b393e473-cb97-4bdf-aa67-a7066007320e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
