<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_s</name>
   <tag></tag>
   <elementGuidId>14ae9be5-1e64-412c-955b-3dd04db8d8aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='woocommerce-product-search-field-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#woocommerce-product-search-field-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56a0b703-08be-4f50-bd11-681c7bae0069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>8871f337-81e1-469b-bd0b-874e76d2d3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>woocommerce-product-search-field-0</value>
      <webElementGuid>9382aa87-e779-41da-abbe-7029ff386147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>379889ce-6269-4af2-9faf-f59c3f37053f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search products…</value>
      <webElementGuid>aa2d0af9-44a1-465c-88ce-ee444c00f71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>2fe014a4-6ce4-499d-852b-f19ddbd32a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;woocommerce-product-search-field-0&quot;)</value>
      <webElementGuid>6a712a29-edb9-4ce4-bc69-d6c0bec74a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='woocommerce-product-search-field-0']</value>
      <webElementGuid>82b756c1-8c6f-4d5e-8ad5-8f891f7d2816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='masthead']/div/div[2]/div/form/input</value>
      <webElementGuid>6ef81687-72c1-42f1-ba98-192de5305db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>11f93f1c-7c5a-489f-9a29-39c1b03a6732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'woocommerce-product-search-field-0' and @placeholder = 'Search products…' and @name = 's']</value>
      <webElementGuid>91cce0b3-2f83-4a49-bce7-b37308540692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
