<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_category_banner_image</name>
   <tag></tag>
   <elementGuidId>e581371e-188b-4f89-9dcc-2ed4e35a7eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.category_banner_image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>77124015-cad5-43c7-ab2b-d3216ace9bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg</value>
      <webElementGuid>785ea6d8-c63c-4cdc-a38d-62d0c8677633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category_banner_image</value>
      <webElementGuid>e28c9dfe-6d03-4c17-a894-22d621dbd25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;col-full&quot;]/div[@class=&quot;wbm_banner_image banner&quot;]/img[@class=&quot;category_banner_image&quot;]</value>
      <webElementGuid>d9399469-efd7-4c29-9ea2-32a05696b718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/img</value>
      <webElementGuid>f313dea7-2a37-4515-8c03-e1ee82ad506c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg')]</value>
      <webElementGuid>254f2e79-99fb-49d7-82c5-8f657bab949f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>f74de850-52c2-4c4f-b9c4-51bb42c19a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg']</value>
      <webElementGuid>65a9d8e4-897a-4896-b604-2f080d31e7b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
